-- 기존 TB_USR 데이터 1건을 삭제하고 PRFL_IMG_FIL_SEQ를 USR_NM 다음에 두어 재생성합니다.
BEGIN;

DROP TABLE ysc.TB_USR;

CREATE TABLE ysc.TB_USR (
    USR_ID             VARCHAR(50)  NOT NULL,
    USR_NM             VARCHAR(100) NOT NULL,
    PRFL_IMG_FIL_SEQ   NUMERIC,
    PWD                VARCHAR(100) NOT NULL,
    ROL                VARCHAR(20)  NOT NULL,
    HP_NO              VARCHAR(20),
    ADR                VARCHAR(255),
    DTL_ADR            VARCHAR(255),
    JOIN_DTM           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FRST_REG_USER_ID   VARCHAR(50)  NOT NULL,
    FRST_REG_DTM       VARCHAR(14)  NOT NULL,
    LAST_MOD_USER_ID   VARCHAR(50)  NOT NULL,
    LAST_MOD_DTM       VARCHAR(14)  NOT NULL,
    CONSTRAINT PK_TB_USR PRIMARY KEY (USR_ID),
    CONSTRAINT FK_TB_USR_PRFL_IMG_FIL
        FOREIGN KEY (PRFL_IMG_FIL_SEQ)
        REFERENCES ysc.FIL_BAS (FIL_SEQ)
);

COMMENT ON COLUMN ysc.TB_USR.PRFL_IMG_FIL_SEQ
    IS '프로필 이미지 파일 일련번호 (FIL_BAS 참조)';

COMMENT ON TABLE ysc.TB_USR IS '사용자 정보';
COMMENT ON COLUMN ysc.TB_USR.USR_ID IS '사용자 아이디';
COMMENT ON COLUMN ysc.TB_USR.USR_NM IS '사용자 이름';
COMMENT ON COLUMN ysc.TB_USR.PWD IS '암호화된 비밀번호';
COMMENT ON COLUMN ysc.TB_USR.ROL IS '사용자 권한';
COMMENT ON COLUMN ysc.TB_USR.HP_NO IS '휴대전화번호';
COMMENT ON COLUMN ysc.TB_USR.ADR IS '주소';
COMMENT ON COLUMN ysc.TB_USR.DTL_ADR IS '상세 주소';
COMMENT ON COLUMN ysc.TB_USR.JOIN_DTM IS '가입 일시';
COMMENT ON COLUMN ysc.TB_USR.FRST_REG_USER_ID IS '최초 등록 사용자 아이디';
COMMENT ON COLUMN ysc.TB_USR.FRST_REG_DTM IS '최초 등록 일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN ysc.TB_USR.LAST_MOD_USER_ID IS '최종 수정 사용자 아이디';
COMMENT ON COLUMN ysc.TB_USR.LAST_MOD_DTM IS '최종 수정 일시 (YYYYMMDDHH24MISS)';

-- 파일 기본정보 테이블 설명
COMMENT ON TABLE ysc.FIL_BAS IS '파일 기본정보';
COMMENT ON COLUMN ysc.FIL_BAS.FIL_SEQ IS '파일 일련번호 (기본키)';
COMMENT ON COLUMN ysc.FIL_BAS.FIL_TYP IS '파일 유형';
COMMENT ON COLUMN ysc.FIL_BAS.FIL_CD IS '파일 구분 코드';
COMMENT ON COLUMN ysc.FIL_BAS.FIL_PTH IS '파일 저장 디렉터리 경로';
COMMENT ON COLUMN ysc.FIL_BAS.FRST_REG_USER_ID IS '최초 등록 사용자 아이디';
COMMENT ON COLUMN ysc.FIL_BAS.FRST_REG_DTM IS '최초 등록 일시';
COMMENT ON COLUMN ysc.FIL_BAS.LAST_MOD_USER_ID IS '최종 수정 사용자 아이디';
COMMENT ON COLUMN ysc.FIL_BAS.LAST_MOD_DTM IS '최종 수정 일시';

-- 파일 상세정보 테이블 설명
COMMENT ON TABLE ysc.FIL_DTL IS '파일 상세정보';
COMMENT ON COLUMN ysc.FIL_DTL.FIL_SEQ IS '파일 일련번호 (FIL_BAS 참조)';
COMMENT ON COLUMN ysc.FIL_DTL.FIL_DTL_SEQ IS '파일 상세 일련번호';
COMMENT ON COLUMN ysc.FIL_DTL.ORG_FIL_NM IS '원본 파일명';
COMMENT ON COLUMN ysc.FIL_DTL.SAV_FIL_NM IS '저장 파일명';
COMMENT ON COLUMN ysc.FIL_DTL.FIL_EXT IS '파일 확장자';
COMMENT ON COLUMN ysc.FIL_DTL.FIL_SZ IS '파일 크기 (byte)';
COMMENT ON COLUMN ysc.FIL_DTL.CONT_TYP IS '파일 콘텐츠 유형 (MIME type)';
COMMENT ON COLUMN ysc.FIL_DTL.FRST_REG_USER_ID IS '최초 등록 사용자 아이디';
COMMENT ON COLUMN ysc.FIL_DTL.FRST_REG_DTM IS '최초 등록 일시';
COMMENT ON COLUMN ysc.FIL_DTL.LAST_MOD_USER_ID IS '최종 수정 사용자 아이디';
COMMENT ON COLUMN ysc.FIL_DTL.LAST_MOD_DTM IS '최종 수정 일시';

COMMIT;
