spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=ysc

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 여러 첨부 파일 업로드 요청(파일별 최대 10MB, 최대 5개)을 허용합니다.
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=55MB

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

solapi.api-key=${SOLAPI_API_KEY}
solapi.api-secret=${SOLAPI_API_SECRET}
solapi.sender=${SOLAPI_SENDER}
