spring.application.name=ysc

spring.datasource.url=jdbc\:postgresql://localhost:15432/ysc
spring.datasource.username=ysc
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=ysc

mybatis.mapper-locations=classpath\:mapper/\*\*/\*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

solapi.api-key=${SOLAPI_API_KEY}
solapi.api-secret=${SOLAPI_API_SECRET}
solapi.sender=${SOLAPI_SENDER}